apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-frontend
  labels:
    app: search-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-frontend
  template:
    metadata:
      labels:
        app: search-frontend
    spec:
      containers:
      - name: search-frontend
        image: search-test-frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: search-cm