// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Book struct {
	ID   uuid.UUID      `json:"id"`
	Name sql.NullString `json:"name"`
}
